// GENERATED by scripts/articles/extract-articles.js from content/articles/who-are-you-if-you-are-not-crushing-it.md
// (Part 2 is the editorial source of truth). Change the brief or
// scripts/articles/articles.js and re-run the script, rather than editing it
// here. Only typography differs from the source (typographic apostrophes),
// internal links are root-relative, and unresolved internal-link
// placeholders are left out with their pointers.
//
// Shape: { url, title, description, h1, deck, meta, author, toc, intro, sections, cta, wordCount }
//   sections = [{ h2, id, kind?, blocks }]; blocks = p | ul | ol | table | sub (an h3 with its blocks)
// Rendered by site-pages.jsx (renderArticlePage); metadata read by scripts/seo/site-meta.js.

window.SITE_ARTICLE_PAGES = window.SITE_ARTICLE_PAGES || {};
window.SITE_ARTICLE_PAGES["who-are-you-if-you-are-not-crushing-it"] = {
  "id": "who-are-you-if-you-are-not-crushing-it",
  "url": "/blog/who-are-you-if-you-are-not-crushing-it/",
  "title": "Who are you if you are not “crushing” it? | Aggelos Mouzakitis",
  "description": "What happens when your identity becomes ‘the one who succeeds’ — and then the promotion doesn’t come or the product fails. Who you are when you’re not crushing it.",
  "h1": "Who are you if you are not “crushing” it?",
  "deck": "When your identity is enmeshed with the concept of constant success.",
  "meta": {"category":"Essay","published":"2026-01-27","publishedLabel":"January 2026","readTime":"7 min read"},
  "author": {"name":"Aggelos Mouzakitis","href":"/about/","image":"/img/aggelos-about.webp","width":840,"height":1050,"alt":"Aggelos Mouzakitis, psychotherapist and article author","credential":"BACP-registered Psychotherapist · MSc Integrative Counselling & Psychotherapy","background":"Background in product and growth · 100+ technology companies advised"},
  "toc": null,
  "intro": [
    {"t":"p","text":"Maybe you got promoted fast or landed the role everyone else wanted. Maybe your first product launch or agency succeeded or you made VP before thirty-five. For some, this would be ‘just successful’ but for you it became ‘the one who succeeds’. That became your identity."},
    {"t":"p","text":"Fast forward some years after the next promotion didn’t come or the product failed. Or you got passed over. Normal career stuff."},
    {"t":"p","text":"Except it didn’t feel normal. It felt like a frecking disaster! Like a personal attack."},
    {"t":"p","text":"I’ve had people argue with me about this for three sessions straight. They want any explanation except the one that threatens the identity. “Maybe I need a better strategy.” “Maybe I’m in the wrong company.” “Maybe I need to pivot industries.” Anything but admitting they built who they are around moving fast, and now they’re not moving, and they don’t know who the fuck they are anymore."}
  ],
  "sections": [
    {"h2":"What actually happened when you succeeded early","id":"what-actually-happened-when-you-succeeded-early", "blocks": [
      {"t":"p","text":"You worked your ass off. You sacrificed weekends, took on projects no one else wanted, stayed late fixing things that weren’t your job, learned faster than your peers, delivered when it mattered. You earned that success, you earned that success, you were genuinely capable and you proved it."},
      {"t":"p","text":"But here’s what happened alongside all that real capability: you started believing your capability was a ticket that guaranteed success in every possible circumstance. You went from “I’m capable and I work hard” to “I’m special and I will figure it out no matter what.”"},
      {"t":"p","text":"That second belief is the problem. Confidence turned into grandiosity and you didn’t notice the shift."}
    ]},
    {"h2":"Confidence vs grandiosity (and why the difference matters)","id":"confidence-vs-grandiosity-and-why-the-difference-matters", "blocks": [
      {"t":"p","text":"Confidence says: I’m capable, I’ve developed real skills, I can handle difficult challenges, I’ve proven I can deliver results when I have the right conditions and resources."},
      {"t":"p","text":"Grandiosity says: I’m special, circumstances don’t really apply to me, I transcend normal limits, if I just think hard enough or work hard enough I can overcome anything because I’m different from other people."},
      {"t":"p","text":"Confidence is grounded in reality. It acknowledges what you’re genuinely good at while recognizing that external conditions matter enormously. It says “I’m capable within circumstances” and adjusts when circumstances change."},
      {"t":"p","text":"Grandiosity is a narcissistic narrative that positions you as someone who overrides circumstances. It says “I’m capable regardless of circumstances” and interprets any failure to override those circumstances as proof you were never actually special."},
      {"t":"p","text":"When you succeed early through real capability, it’s incredibly easy to slip from confidence into grandiosity without realizing it. Because when things are working, both beliefs feel the same. Both make you feel powerful and driven and willing to take on challenges. The difference only becomes visible when things stop working."},
      {"t":"p","text":"Someone with confidence hits a wall and thinks: “These conditions are harder than the ones I succeeded in before. What needs to change about my approach or my situation?” Someone with grandiosity hits the same wall and thinks: “I should be able to figure this out. If I can’t, it means I was never actually special, and everything I believed about myself was a lie.”"},
      {"t":"p","text":"See the difference? Confidence adjusts to reality. Grandiosity makes failure an identity crisis."}
    ]},
    {"h2":"What 2025-2026 is teaching high achievers","id":"what-2025-2026-is-teaching-high-achievers", "blocks": [
      {"t":"p","text":"The economy right now is fundamentally different than when you were rising fast. AI is disrupting everything about how work gets done and who gets rewarded for what. Companies are restructuring constantly, budgets are frozen, roles that used to exist don’t exist anymore. Literally everyone I know in product and growth and leadership is suffering more or less."},
      {"t":"p","text":"But you don’t know that because you’re comparing yourself to what you think other high achievers are doing based on their LinkedIn posts. You don’t see that they’re also struggling, also anxious, also wondering if something is wrong with them. You just see the curated version and assume you’re the only one who can’t figure it out anymore."},
      {"t":"p","text":"I had a client, exceptionally talented product leader, who built her career on being the person who could turn around struggling products. She’d done it three times in a row, always came in and fixed what was broken, always delivered results within six months. She genuinely was that good."},
      {"t":"p","text":"Then she took a role in 2024 at a company that was struggling worse than she realized, in a market contracting faster than anyone predicted, with a product that had fundamental problems she couldn’t fix without resources the company didn’t have. She tried everything that had worked before, put in the same effort, applied the same strategic frameworks. Nothing moved."},
      {"t":"p","text":"She came to therapy convinced something was wrong with her specifically. Had she lost her edge? Was she burnt out? Did she not actually know what she was doing? She was torturing herself trying to figure out what had changed about her capabilities, when what had actually changed was everything external to her capabilities."},
      {"t":"p","text":"The company was underfunded in a market where funding had dried up. The product needed engineering resources that weren’t available. The customer segment was cutting budgets across the board. She was as capable as she’d always been, but capability doesn’t override reality when reality is fundamentally hostile to what you’re trying to do."},
      {"t":"p","text":"But she couldn’t see that because her identity was built on grandiosity, not confidence. The narrative said circumstances don’t matter for people like her, that she’s special enough to overcome anything. So when she couldn’t make it work, the only explanation her framework allowed was that she wasn’t actually special, that she’d been fooling herself all along."}
    ]},
    {"h2":"Reality crisis or identity crisis?","id":"reality-crisis-or-identity-crisis", "blocks": [
      {"t":"p","text":"You think you’re having an identity crisis because you built your identity on being someone who succeeds and now you’re not succeeding the way you used to. But what you’re actually having is a reality crisis. You’re running into the limits of the grandiose narrative that your capability overrides circumstances."},
      {"t":"p","text":"You were capable before and you’re capable now. What changed isn’t you, what changed is the environment you’re operating in. But your framework doesn’t allow for that interpretation because your framework says “I’m someone who figures it out regardless of conditions.” So when you can’t figure it out, you conclude you were never actually special, that it was all an illusion, that your previous success was just luck."},
      {"t":"p","text":"That’s the trap. You’re either special and invincible and able to overcome any circumstance, or you’re a fraud who never deserved the success you had. There’s no middle ground where you’re genuinely capable AND circumstances matter enormously AND sometimes capable people can’t overcome hostile conditions AND that doesn’t mean anything about whether you were ever actually good."},
      {"t":"p","text":"The high achiever in your network who just announced a new role? They applied to forty positions and got rejected from thirty-nine and they’re terrified they won’t be able to perform because the expectations are unrealistic. The founder posting about growth metrics? They’re burning through runway faster than planned and having panic attacks about the next funding round. The person who seems to have it figured out? They’re also in therapy, also anxious, also wondering if they’ve lost whatever made them successful."},
      {"t":"p","text":"Nobody posts the real version. Everyone is managing their personal brand. So you’re comparing your internal experience of struggle to everyone else’s carefully curated external presentation, and you’re concluding that you’re the problem when you’re actually just the only one being honest with yourself."}
    ]},
    {"h2":"What you actually need to do","id":"what-you-actually-need-to-do", "blocks": [
      {"t":"p","text":"Separate your capability from the grandiose narrative you built around it. You are capable, you did earn your success, you do have real skills and strategic thinking and ability to deliver results. That was true then and it’s true now."},
      {"t":"p","text":"What’s also true is that circumstances matter more than you wanted to believe. The market matters, the economy matters, the specific conditions of your company matter, the resources available to you matter, the timing matters. Being capable doesn’t override these things, it just gives you better odds in favorable conditions and helps you survive longer in unfavorable ones."},
      {"t":"p","text":"You’re not struggling because you lost your capability or because you were never actually good. This is the story the little voice tells you quietly but the truth is you’re struggling because you’re trying to operate in conditions that are fundamentally harder than the conditions you succeeded in before, and because you built an identity around grandiosity instead of confidence."},
      {"t":"p","text":"That’s hard to accept because it means giving up the narcissistic narrative that made you feel powerful and invincible. It means accepting that you’re subject to the same external forces as everyone else, that being good at what you do doesn’t make you immune to market conditions or economic realities or structural changes. It means being human instead of being exceptional."},
      {"t":"p","text":"Most people don’t feel relieved when they first accept this, they feel smaller and more vulnerable and less special. The relief comes later when you realize that not being invincible doesn’t mean you’re not capable. It just means you’re operating in reality instead of in a grandiose fantasy about your own exceptionalism. And reality is where you can actually make different choices instead of just beating yourself up for not being able to override circumstances through pure force of will."},
      {"t":"p","text":"You’re capable and you’re struggling and both of those things can be true at the same time. That’s not a personal failure, that’s what it looks like to be a capable person operating in difficult conditions. Stop making it mean something about whether you were ever actually good, and start dealing with the actual reality of what’s changed and what you need to do differently given those changes."}
    ]}
  ],
  "cta": null,
  "close": {"label":"Contact","text":"If you have already spent a long time thinking about something and want to talk about it directly, get in touch.","actions":[{"label":"Considering therapy","href":"/considering-therapy/"},{"label":"Book a consultation","href":"/contact/"}]},
  "wordCount": 1623
};
