// site-articles.jsx — the articles listed on /blog/ (Writing), newest first.
//
// GENERATED by scripts/articles/extract-articles.js from content/articles/
// (Part 2 is the editorial source of truth). Change the brief or
// scripts/articles/articles.js and re-run the script, rather than editing it
// here. Only typography differs from the source (typographic apostrophes),
// internal links are root-relative, and unresolved internal-link
// placeholders are left out with their pointers.

window.SITE_ARTICLES = [
  {"id":"work-anxiety","url":"/work-anxiety/","h1":"Work Anxiety: Why Work Gets Into Your Head and What to Do About It","deck":"Work anxiety can come from the job, from patterns that work brings out, or from both. Understanding the sequence helps you decide what needs to change.","category":"Guide","published":"2026-10-01T22:04:00+01:00","publishedLabel":"October 2026","readTime":"20 min read","related":{"label":"Anxiety & Overthinking","href":"/anxiety-overthinking/"}}
];
