// site-nav.jsx — the header and footer wording, from the canonical copy.
//
// GENERATED by scripts/copy/extract-canonical.py from the canonical document
// ("Aggelos Mouzakitis — Canonical Website Copy & Metadata"). The wording is
// the approved wording: change it in the document and re-run the script,
// rather than editing it here. Only typography differs from the source
// (typographic apostrophes; → drawn by the UI).
//
// Loaded on every page before site-chrome.js, which renders it.

window.SITE_NAV = {
  "nav": {
    "items": [
      {
        "label": "Home",
        "href": "/"
      },
      {
        "label": "About",
        "href": "/about/"
      },
      {
        "label": "Services",
        "items": [
          {
            "label": "Individual Psychotherapy",
            "href": "/individual-psychotherapy/"
          },
          {
            "label": "Couples Therapy",
            "href": "/couples-therapy/"
          },
          {
            "label": "Professional Coaching",
            "href": "/professional-coaching/"
          },
          {
            "label": "Therapy for Men in Tech & Business",
            "href": "/therapy-for-men-in-tech/"
          },
          {
            "label": "Therapy for Executives & Senior Leaders",
            "href": "/therapy-for-executives/"
          },
          {
            "label": "Therapy for Entrepreneurs, Founders & Business Owners",
            "href": "/therapy-for-founders/"
          },
          {
            "label": "Greek-speaking Psychotherapy",
            "href": "/greek-speaking-psychotherapist/"
          }
        ]
      },
      {
        "label": "Resources",
        "items": [
          {
            "label": "Considering Therapy",
            "href": "/considering-therapy/"
          },
          {
            "label": "Therapy vs Coaching",
            "href": "/therapy-vs-coaching/"
          },
          {
            "label": "Writing",
            "href": "/blog/"
          },
          {
            "label": "Free Tools",
            "href": "/free-tools/"
          },
          {
            "label": "Reviews",
            "href": "/reviews/"
          }
        ]
      },
      {
        "label": "FAQ",
        "href": "/faq/"
      }
    ],
    "cta": {
      "label": "Book a consultation",
      "href": "/contact/"
    }
  },
  "footer": {
    "brand": "Aggelos.",
    "tagline": "BACP-registered psychotherapist · Background in tech, product & growth",
    "groups": [
      {
        "label": "Work with me",
        "items": [
          {
            "label": "Individual Psychotherapy",
            "href": "/individual-psychotherapy/"
          },
          {
            "label": "Couples Therapy",
            "href": "/couples-therapy/"
          },
          {
            "label": "Professional Coaching",
            "href": "/professional-coaching/"
          }
        ]
      },
      {
        "label": "Who I work with",
        "items": [
          {
            "label": "Men in Tech & Demanding Careers",
            "href": "/therapy-for-men-in-tech/"
          },
          {
            "label": "Founders & Business Owners",
            "href": "/therapy-for-founders/"
          },
          {
            "label": "Executives & Leaders",
            "href": "/therapy-for-executives/"
          },
          {
            "label": "Greek-speaking Psychotherapy",
            "href": "/greek-speaking-psychotherapist/"
          }
        ]
      },
      {
        "label": "Common problems",
        "items": [
          {
            "label": "Relationships & Separation",
            "href": "/relationship-problems-men/"
          },
          {
            "label": "Work & Relationships",
            "href": "/work-affecting-relationship/"
          },
          {
            "label": "Burnout & Can’t Switch Off",
            "href": "/executive-burnout-therapy/"
          },
          {
            "label": "Career Change & Decisions",
            "href": "/career-transition-therapy/"
          },
          {
            "label": "Anxiety & Overthinking",
            "href": "/anxiety-overthinking/"
          },
          {
            "label": "Achievement & Self-Worth",
            "href": "/achievement-self-worth/"
          }
        ]
      },
      {
        "label": "Practice",
        "items": [
          {
            "label": "About",
            "href": "/about/"
          },
          {
            "label": "Considering Therapy",
            "href": "/considering-therapy/"
          },
          {
            "label": "Therapy vs Coaching",
            "href": "/therapy-vs-coaching/"
          },
          {
            "label": "Writing",
            "href": "/blog/"
          },
          {
            "label": "Free Tools",
            "href": "/free-tools/"
          },
          {
            "label": "FAQ",
            "href": "/faq/"
          },
          {
            "label": "Reviews",
            "href": "/reviews/"
          },
          {
            "label": "Contact",
            "href": "/contact/"
          }
        ]
      }
    ],
    "legal": [
      {
        "label": "Confidentiality",
        "href": "/confidentiality/"
      }
    ],
    "rights": "© 2026 Aggelos Mouzakitis. All rights reserved."
  }
};
